version: '3.8'

services:
  book-db:
    image: postgres:latest
    container_name: book-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: book_service
    ports:
      - "5434:5432"
    volumes:
      - book-db-data:/var/lib/postgresql/data

  reservation-db:
    image: postgres:latest
    container_name: reservation-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservation_service
    ports:
      - "5435:5432"
    volumes:
      - reservation-db-data:/var/lib/postgresql/data

volumes:
  book-db-data:
  reservation-db-data: 